name: test
on: [push]
jobs:
  kotlin:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # ratchet:actions/checkout@v2
        with:
          java-version: '11'
      - run: ./gradlew testDebugUnitTest
